# Generated by Django 4.1.5 on 2023-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
