# Generated by Django 4.1.5 on 2023-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0002_line_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="number",
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
