# Generated by Django 4.1.5 on 2023-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0003_quote_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="number",
            field=models.IntegerField(max_length=8, unique=True),
        ),
    ]
