# Generated by Django 4.1.5 on 2023-02-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0004_alter_quote_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="number",
        ),
    ]
