# Generated by Django 4.1.5 on 2023-02-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0005_remove_quote_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(max_length=80)),
                ("last_name", models.TextField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SENT", "Sent"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quote",
            name="creation_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
