# Generated by Django 4.1.5 on 2023-02-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0006_user_quote_creation_date_quote_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="quote",
        ),
        migrations.AddField(
            model_name="quote",
            name="lines",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quoting.line",
            ),
        ),
    ]
