# Generated by Django 4.1.5 on 2023-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0008_remove_quote_lines_line_quote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                ],
                default="DRAFT",
                max_length=16,
            ),
        ),
    ]
